# Generated by Django 5.2.3 on 2025-07-03 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_privatechatroom_is_deleted_for_participant_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('max_members', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Chat Room',
                'verbose_name_plural': 'Group Chat Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.groupchatroom')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Invitation',
                'verbose_name_plural': 'Group Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.groupchatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System')], default='text', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.groupchatroom')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.groupmessage')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Message',
                'verbose_name_plural': 'Group Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='chat.groupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Message Read Status',
                'verbose_name_plural': 'Group Message Read Statuses',
            },
        ),
        migrations.AddIndex(
            model_name='groupchatroom',
            index=models.Index(fields=['name'], name='chat_groupc_name_1bf074_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatroom',
            index=models.Index(fields=['created_at'], name='chat_groupc_created_bad986_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchatroom',
            index=models.Index(fields=['is_active'], name='chat_groupc_is_acti_4605d8_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['invited_user', 'status'], name='chat_groupi_invited_a904a6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['group', 'status'], name='chat_groupi_group_i_c46c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['expires_at'], name='chat_groupi_expires_934f4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupinvitation',
            unique_together={('group', 'invited_user')},
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'role'], name='chat_groupm_group_i_c387b7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user'], name='chat_groupm_user_id_360030_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['joined_at'], name='chat_groupm_joined__a499cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group', 'timestamp'], name='chat_groupm_group_i_2ff167_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['sender', 'timestamp'], name='chat_groupm_sender__bdf041_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['timestamp'], name='chat_groupm_timesta_026aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['message_type'], name='chat_groupm_message_2d7fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereadstatus',
            index=models.Index(fields=['message', 'user'], name='chat_groupm_message_0dc62c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereadstatus',
            index=models.Index(fields=['user', 'read_at'], name='chat_groupm_user_id_0fbdf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
