# Generated by Django 5.2.3 on 2025-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupchatroom_groupinvitation_groupmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='max_members',
            field=models.PositiveIntegerField(default=250, editable=False),
        ),
    ]
