# Generated by Django 5.2.3 on 2025-07-17 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_groupchatroom_max_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
