# Generated by Django 5.2.3 on 2025-07-18 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_groupmessage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='group_messages/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'zip', 'mp4'])]),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_messages/images/'),
        ),
    ]
