# Generated by Django 5.2.3 on 2025-07-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groupmessage_docs_groupmessage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='docs',
            new_name='doc',
        ),
    ]
