# Generated by Django 5.2.3 on 2025-07-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_docs_groupmessage_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('doc', 'Doc')], default='text', max_length=20),
        ),
    ]
